### ISSUE TITLE
After adding admin reset the input fields based on error or admin added 

### ISSUE THREAD

**Issue by Abhishek-Mamdabad** [Abhishek-Mamdabad/college-attendence-management-system#1]
After adding admin reset the input fields based on error or admin added . Try to use useEffect hook for state management

**Comment by sashank49** [comment]
I can do it. Is the issue still open

**Comment by Abhishek-Mamdabad** [comment]
yes

**Comment by Abhishek-Mamdabad** [comment]
Done with the useeffect
